
name: Basic

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Linelint
      uses: fernandrone/linelint@master
      id: linelint

    - name: Check signed commits in PR
      uses: 1Password/check-signed-commits-action@v1

    - name: Run Clippy
      run: |
       cargo clippy -p deepseek-api --all-targets --all-features
       cargo clippy -p basic --all-targets --all-features
       cargo clippy -p chat-stream --all-targets --all-features
       cargo clippy -p fim --all-targets --all-features
       cargo clippy -p sync-basic --all-targets --all-features
       cargo clippy -p ds-cli --all-targets --all-features

    - name: Build
      run: |
       cargo build -p deepseek-api --all-targets
       cargo build -p basic --all-targets
       cargo build -p chat-stream --all-targets
       cargo build -p fim --all-targets
       cargo build -p sync-basic --all-targets
       cargo build -p ds-cli --all-targets

    - name: Run tests
      run: cargo test -p deepseek-api --verbose

    - name: Publish crates
      uses: katyo/publish-crates@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          path: "deepseek-api"
